import Sidebar from "@/shared/sidebar";
import Head from "next/head";

function AddMachine() {
  return (
    <>
      <Head>
        <title>Add Machine</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen flex">
        {/* sideBar */}
        <div className="w-72 h-screen fixed">
          <Sidebar />
        </div>
        {/* content */}
        <div className="w-[20%]" />
        <div className="w-[80%] h-full p-10 grid place-items-center">
          <div className="w-96 flex flex-col p-5 border-t-4 border-t-cblue border border-gray-400 rounded-lg">
            <div className="text-3xl text-center">Add Machine</div>
            <div className="h-8" />
            <input
              className="p-2 px-5 border border-cbluel rounded-lg focus:border-cblue focus:border-2"
              type="text"
              placeholder="Machine Id"
            />

            <div className="h-8" />
            <input
              className="p-2 px-5 border border-cbluel rounded-lg focus:border-cblue focus:border-2"
              type="password"
              placeholder="Password"
            />

            <div className="h-8" />
            <input
              className="p-2 px-5 border border-cbluel rounded-lg focus:border-cblue focus:border-2"
              type="password"
              placeholder="Confirm Password"
            />

            <div className="h-8" />

            <button className="p-2 text-white border border-cblue bg-cblue rounded-md hover:border hover:border-cblue hover:text-cblue hover:bg-white">
              ADD MACHINE
            </button>
          </div>
        </div>
      </main>
    </>
  );
}

export default AddMachine;
