import Sidebar from "@/shared/sidebar";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen flex">
        {/* sideBar */}
        <div className="w-96 h-full">
          <Sidebar />
        </div>
        {/* content */}
        <div className="w-full h-full"></div>
      </main>
    </>
  );
}
