import { MachineModel } from "@/models/machineModel";
import Sidebar from "@/shared/sidebar";
import axios from "axios";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { PulseLoader } from "react-spinners";

function MachineTableRow({ machine }: { machine: MachineModel }) {
  return (
    <tr className="bg-white border-b">
      <th className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap text-left">
        {machine.mid}
      </th>
      <td className="px-6 py-4 text-left uppercase ">{machine.mstatus}</td>
      <td className="px-6 py-4 text-right">{machine.location}</td>
      <td className="px-6 py-4 text-right">
        <Link href="/" className="font-medium text-cblue hover:underline">
          Change Password
        </Link>
      </td>
    </tr>
  );
}

function ViewMachines() {
  const [isSearchLoading, setIsSearchLoading] = useState(false);
  const [pgVal, setPgVal] = useState(1);
  const [totPages, setTotPages] = useState(1);
  const [queryObj, setQueryObj] = useState({
    mid: "",
    mstatus: "",
    location: "",
  });
  const [machineList, setMachineList] = useState<MachineModel[]>([]);

  async function getAllMachines() {
    setIsSearchLoading(true);
    if (!process.env.NEXT_PUBLIC_SERVER_URL) throw "Server Url Not Set";
    const url =
      process.env.NEXT_PUBLIC_SERVER_URL + "/auth/admin/getAllMachines";
    try {
      var res = await axios.get(url, {
        params: {
          mid: queryObj.mid,
          mstatus: queryObj.mstatus,
          location: queryObj.location,
          page: pgVal,
        },
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${localStorage.getItem("Token")}`,
        },
      });

      if (res.status === 200) {
        setMachineList(res.data.result.machines);
        setTotPages(res.data.result.numOfPages);
      }
    } catch (e: any) {}

    setIsSearchLoading(false);
  }

  useEffect(() => {
    getAllMachines();
  }, [pgVal]);

  return (
    <>
      <Head>
        <title>View Machines</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen flex">
        {/* sideBar */}
        <div className="w-72 h-screen fixed">
          <Sidebar />
        </div>
        {/* content */}
        <div className="w-[20%]" />
        <div className="w-[80%] h-full p-10 flex flex-col">
          {/* Filter Box */}
          <div className="w-full p-10 flex flex-col bg-slate-200 rounded-md">
            <div className="text-4xl">Filter</div>
            <div className="h-10" />
            <div className="w-full grid gap-5 grid-cols-2 md:grid-cols-3">
              {/*  */}
              <div className="flex flex-col">
                <div className="font-semibold text-sm ml-1">Machine Id</div>
                <div className="h-2" />
                <input
                  className="p-1 px-2 rounded-md border border-gray-400"
                  value={queryObj.mid}
                  onChange={(v) =>
                    setQueryObj((f) => ({ ...f, mid: v.target.value }))
                  }
                  type="text"
                />
              </div>

              {/*  */}
              <div className="flex flex-col">
                <div className="font-semibold text-sm ml-1">Status</div>
                <div className="h-2" />
                {/* <input
                  className="p-1 px-2 rounded-md border border-gray-400"
                  type="text"
                /> */}
                <select
                  className="p-1 px-2 rounded-md border border-gray-400"
                  onChange={(v) =>
                    setQueryObj((f) => ({ ...f, mstatus: v.target.value }))
                  }>
                  <option>ALL</option>
                  <option>CONNECTED</option>
                  <option>DISCONNECTED</option>
                </select>
              </div>

              {/*  */}
              <div className="flex flex-col">
                <div className="font-semibold text-sm ml-1">Location</div>
                <div className="h-2" />
                <input
                  className="p-1 px-2 rounded-md border border-gray-400"
                  value={queryObj.location}
                  onChange={(v) =>
                    setQueryObj((f) => ({ ...f, location: v.target.value }))
                  }
                  type="text"
                />
              </div>

              {/*  */}
              <div className="flex flex-col col-span-3">
                <div className="h-7" />
                <button
                  className="p-1 rounded-md border border-cblue text-white bg-cblue hover:text-cblue hover:bg-transparent"
                  onClick={getAllMachines}>
                  {isSearchLoading ? <PulseLoader /> : "Search"}
                </button>
              </div>
            </div>
          </div>

          {/* table */}
          <div className="h-10" />
          <div className="w-full p-10 flex flex-col bg-slate-200 rounded-md">
            {/* table */}
            <div className="w-full overflow-x-auto rounded-lg">
              <table className="w-full text-sm text-left text-gray-500">
                <thead className="text-gray-900 uppercase bg-gray-50">
                  <tr>
                    <th className="px-6 py-3 text-left">Machine id</th>
                    <th className="px-6 py-3 text-left">status</th>
                    <th className="px-6 py-3 text-right">Location</th>
                    <th className="px-6 py-3 text-right">Action</th>
                  </tr>
                </thead>
                <tbody>
                  {machineList.map((machine, i) => (
                    <MachineTableRow key={i} machine={machine} />
                  ))}
                </tbody>
              </table>
            </div>

            {/* pagination bar */}
            <div className="h-3" />
            <div className="w-full p-3 grid place-items-center">
              <div className="flex border border-cblue rounded-xl">
                <button
                  className="p-2 border-r border-cblue bg-cblue text-white hover:bg-transparent hover:text-cblue rounded-l-lg"
                  onClick={() => {
                    if (pgVal > 1) setPgVal((v) => (v -= 1));
                  }}>
                  Previous
                </button>
                <div className="flex px-3 justify-center items-center">
                  <input
                    className="w-10 px-1 m-1 mr-3 rounded-md border text-center"
                    // value={1}
                    type="text"
                    pattern="[0-9]*"
                    value={pgVal}
                    onChange={(e) => {
                      const num =
                        parseInt(e.target.value.replace("/D/g", "")) || 0;
                      if (num > totPages) return;
                      setPgVal(num);
                    }}
                  />
                  <div className="text-gray-600 text-lg mr-1">/ 1</div>
                </div>
                <button
                  className="p-2 border-l border-cblue bg-cblue text-white hover:bg-transparent hover:text-cblue rounded-r-lg"
                  onClick={() => {
                    if (pgVal < totPages) setPgVal((v) => (v += 1));
                  }}>
                  Next
                </button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

export default ViewMachines;
